spring:
  datasource:
    url: jdbc:mysql://localhost:3306/movieclub
    username: root
    password:
  liquibase:
    contexts: prod
  web:
    resources:
      static-locations: classpath:/static/,file:///E:/uploads/
app:
  storage:
    location: E:/uploads/